spring.datasource.url=jdbc:postgresql://ep-green-bread-a1g7d0co-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ev1YIk7LDxNc
spring.datasource.driver-class-name=org.postgresql.Driver
#JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#server port
server.port=8080

#JWT service
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000
